service: nestjs-blog-api

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - tests/**
    - .gitignore
    - .git/**

functions:
  main:
    handler: dist/src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'