export enum ENUM_POST_STATUS_CODE_ERROR {
    POST_NOT_FOUND_ERROR = 5100,
    POST_PAYLOAD_TYPE_INVALID_ERROR = 5101,
    POST_EXIST_ERROR = 5102,
    POST_IS_ACTIVE_ERROR = 5103,
    POST_INACTIVE_ERROR = 5104,
    POST_USED_ERROR = 5105,
}
