name: SSH Deploy to EC2 and Docker Private Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Private Repository
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t phongnv96/nestjs-blog:latest .
          docker push phongnv96/nestjs-blog:latest
        env:
          DOCKER_REGISTRY_URL: phongnv96/nestjs-blog

      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the Docker image from the private repository
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
            docker pull phongnv96/nestjs-blog:latest

            # Stop and remove the existing container (if applicable)
            docker stop nestjs-blog || true
            docker rm nestjs-blog || true

            # Run the Docker container with the new image
            docker run -d -p 80:3000 --name nestjs-blog phongnv96/nestjs-blog:latest
